on:
    pull_request:
        branches:
            - main

jobs:
    changes:
        runs-on: ubuntu-latest
        steps:
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                    pack1: "pack1/**"
                    pack2: "pack2/**"
        outputs:
            # Expose matched filters as job 'packages' output variable
            packages: ${{ steps.filter.outputs.changes }}

    build:
        needs: changes
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: ${{ fromJson(needs.changes.outputs.packages) }}
        steps:
            - uses: actions/checkout@v2
            - name: Build ${{ matrix.package }}
              run: cd ${{ matrix.package }}
            - run: echo "Building ${{ matrix.package }}..."
            - run: exit 1

    packages_result:
        if: ${{ always() }}
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - run: exit 0