on:
    pull_request:
        branches:
            - main

jobs:
    changes:
        runs-on: ubuntu-latest
        steps:
            # Determine changed subpaths to run the matrix on
            # See https://github.com/dorny/paths-filter/tree/v2/#examples
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                    pack1: "pack1/**"
                    pack2: "pack2/**"
        outputs:
            # Expose matched filters as job 'packages' output variable
            packages: ${{ steps.filter.outputs.changes }}

    build:
        needs: changes
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: ${{ fromJson(needs.changes.outputs.packages) }}
        steps:
            - uses: actions/checkout@v2
            - name: Build ${{ matrix.package }}
              run: cd ${{ matrix.package }}
            - run: echo "Building ${{ matrix.package }}..."

    packages_result:
        # Require all jobs under `build` to have succeeded
        # See https://github.com/orgs/community/discussions/26822
        if: ${{ always() }}
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - run: exit 1
              if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}