on:
    pull_request:
        branches:
            - main

jobs:
    check_changes:
        runs-on: ubuntu-latest
        steps:
            - uses: dorny/paths-filter@v2
              id: changes
              with:
                  filters: |
                    package1:
                        - "pack1/**"
                    package2:
                        - "pack2/**"
        outputs:
            package1: ${{ steps.changes.outputs.package1 }}
            package2: ${{ steps.changes.outputs.package2 }}

    Package1:
        runs-on: ubuntu-latest
        needs: check_changes
        steps:
            - run: echo "Package1 was changed"
              if: needs.check_changes.outputs.package1 == 'true'


    Package2:
        runs-on: ubuntu-latest
        needs: check_changes
        steps:
            - run: echo "Package2 was changed"
              if: needs.check_changes.outputs.package2 == 'true'